### ISSUE TITLE
Referencing jar files on template path

### ISSUE THREAD

**Issue by jodiestjohn** [teatrove/teatrove#212]
I am trying to bundle templates in  jar and point to it on the template path.  I have tried various ways to do this but I cannot get it to work.  Here is an example stack trace when teaservlet starts up:

2012-12-04 12:36:16,621    [startup] ERROR root -  not a jar url: c://Users/johnjo/git/watch.espn-web-app/target/services/vESPN360But/Templates/espn360-butler.jar/
java.lang.RuntimeException: not a jar url: c://Users/johnjo/git/watch.espn-web-app/target/services/vESPN360But/Templates/espn360-butler.jar/
    at com.go.tea.util.JarCompilationProvider$JarOfTemplates.makeJarUrlFromFile(JarCompilationProvider.java:197)
    at com.go.tea.util.JarCompilationProvider$JarOfTemplates.<init>(JarCompilationProvider.java:148)
    at com.go.tea.util.JarCompilationProvider.<init>(JarCompilationProvider.java:51)
    at com.go.tea.engine.TemplateSourceImpl.createProvider(TemplateSourceImpl.java:760)
    at com.go.teaservlet.TeaServletTemplateSource.createProvider(TeaServletTemplateSource.java:254)
    at com.go.tea.engine.TemplateSourceImpl.parseProviders(TemplateSourceImpl.java:741)
    at com.go.tea.engine.TemplateSourceImpl.createCompiler(TemplateSourceImpl.java:530)
    at com.go.tea.engine.TemplateSourceImpl.createCompiler(TemplateSourceImpl.java:518)
    at com.go.tea.engine.TemplateSourceImpl.actuallyCompileTemplates(TemplateSourceImpl.java:643)
    at com.go.tea.engine.TemplateSourceImpl.actuallyCompileTemplates(TemplateSourceImpl.java:577)
    at com.go.teaservlet.TeaServletTemplateSource.compileTemplates(TeaServletTemplateSource.java:312)
    at com.go.teaservlet.TeaServletTemplateSource.compileTemplates(TeaServletTemplateSource.java:277)
    at com.go.teaservlet.TeaServletTemplateSource.compileTemplates(TeaServletTemplateSource.java:229)
    at com.go.tea.engine.TemplateSourceImpl.compileTemplates(TemplateSourceImpl.java:193)
    at com.go.teaservlet.TeaServletEngineImpl.compileTemplates(TeaServletEngineImpl.java:90)
    at com.go.teaservlet.TeaServletEngineImpl.startEngine(TeaServletEngineImpl.java:142)
    at com.go.teaservlet.TeaServlet$Initializer.init(TeaServlet.java:256)
    at com.go.teaservlet.TeaServlet$Initializer.call(TeaServlet.java:219)
    at com.go.teaservlet.TeaServlet.init(TeaServlet.java:202)
    at go.barista.servlet.TQTeaServlet.init(TQTeaServlet.java:77)
    at go.barista.http.ServletPool.createServlet(ServletPool.java:297)
    at go.barista.http.ServletPool.get(ServletPool.java:217)
    at go.barista.http.ServletPool.preload(ServletPool.java:263)
    at go.barista.http.HttpServletDispatcher.init(HttpServletDispatcher.java:221)
    at go.barista.http.HttpServletDispatcher.init(HttpServletDispatcher.java:133)
    at go.barista.http.HttpServer.createServletDispatchers(HttpServer.java:540)
    at go.barista.http.HttpServer.init(HttpServer.java:307)
    at go.barista.http.HttpServer.access$100(HttpServer.java:54)
    at go.barista.http.HttpServer$2.run(HttpServer.java:213)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.MalformedURLException: unknown protocol: c
    at java.net.URL.<init>(URL.java:574)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URL.<init>(URL.java:413)
    at com.go.tea.util.JarCompilationProvider$JarOfTemplates.makeJarUrlFromFile(JarCompilationProvider.java:195)
    ... 29 more

My path looks like this:

```
    <path>file:c:/Users/johnjo/git/watch.espn-web-app/target/services/vESPN360But/Templates/espn360-butler.jar;
        file:c:/Users/johnjo/git/watch.espn-web-app/target/services/vESPN360But/Templates/includes.jar
    </path>
```

The TemplateSourceImpl class finds these files correctly and passes them to the JarCompilationProvider class.  However that class them tries to create a URL from the file path and throws the exception.

**Comment by nicholashagen** [comment]
Fixed from Pull Request #213
